#pragma once
#include <map>
#include <set>
#include <list>
#include <array>
#include <vector>
#include <string>
#include <memory>
#include <type_traits>
#include "TemplateWrap.h"

DEFINE_NS_TEMPLATE_BEGIN_WITH_2_PARAMS( std, array, typename, size_t )
	REGIST_DEFAULT_CONSTRUCTOR()
	REGIST_ARRAY( P0, size )
	REGIST_ITERATOR( iterator )
	REGIST_ITERATOR( reverse_iterator )
	REGIST_CLASSMETHOD_OVERLOAD( iterator(), begin, begin )
	REGIST_CLASSMETHOD_OVERLOAD( iterator(), end, end )
	REGIST_CLASSMETHOD_OVERLOAD( reverse_iterator(), rbegin, rbegin )
	REGIST_CLASSMETHOD_OVERLOAD( reverse_iterator(), rend, rend )
DEFINE_TEMPLATE_END()

DEFINE_NS_TEMPLATE_BEGIN_WITH_2_PARAMS( std, pair, typename, typename )
	REGIST_DEFAULT_CONSTRUCTOR()
	REGIST_CLASSMEMBER( first )
	REGIST_CLASSMEMBER( second )
DEFINE_TEMPLATE_END()

DEFINE_NS_TEMPLATE_BEGIN_WITH_1_PARAM( std, set, typename )
	REGIST_DEFAULT_CONSTRUCTOR()
	REGIST_ITERATOR( iterator )
	REGIST_ITERATOR( reverse_iterator )
	REGIST_CLASSMETHOD( empty )
	REGIST_CLASSMETHOD( size )
	REGIST_CLASSMETHOD_WITH_LAMBDA( iterator( iterator, const P0& ), [this]( iterator i, const P0& e ) { return this->insert( i, e ); }, insert )
	REGIST_CLASSMETHOD_OVERLOAD( iterator( iterator ), erase, erase )
	REGIST_CLASSMETHOD_OVERLOAD( iterator(), begin, begin )
	REGIST_CLASSMETHOD_OVERLOAD( iterator(), end, end )
	REGIST_CLASSMETHOD_OVERLOAD( reverse_iterator(), rbegin, rbegin )
	REGIST_CLASSMETHOD_OVERLOAD( reverse_iterator(), rend, rend )
	REGIST_CLASSMETHOD_OVERLOAD( iterator(const P0&), find, find )
DEFINE_TEMPLATE_END()

DEFINE_NS_TEMPLATE_BEGIN_WITH_1_PARAM( std, multiset, typename )
	REGIST_DEFAULT_CONSTRUCTOR()
	REGIST_ITERATOR( iterator )
	REGIST_ITERATOR( reverse_iterator )
	REGIST_CLASSMETHOD( empty )
	REGIST_CLASSMETHOD( size )
	REGIST_CLASSMETHOD_WITH_LAMBDA( iterator( iterator, const P0& ), [this]( iterator i, const P0& e ) { return this->insert( i, e ); }, insert )
	REGIST_CLASSMETHOD_OVERLOAD( iterator( iterator ), erase, erase )
	REGIST_CLASSMETHOD_OVERLOAD( iterator(), begin, begin )
	REGIST_CLASSMETHOD_OVERLOAD( iterator(), end, end )
	REGIST_CLASSMETHOD_OVERLOAD( reverse_iterator(), rbegin, rbegin )
	REGIST_CLASSMETHOD_OVERLOAD( reverse_iterator(), rend, rend )
	REGIST_CLASSMETHOD_OVERLOAD( iterator(const P0&), find, find )
DEFINE_TEMPLATE_END()

DEFINE_NS_TEMPLATE_BEGIN_WITH_2_PARAMS( std, map, typename, typename )
	REGIST_DEFAULT_CONSTRUCTOR()
	REGIST_ITERATOR( iterator )
	REGIST_ITERATOR( reverse_iterator )
	REGIST_CLASSMETHOD( empty )
	REGIST_CLASSMETHOD( size )
	REGIST_CLASSMETHOD_WITH_LAMBDA( iterator( iterator, const std::pair<P0, P1>& ), [this]( iterator i, const std::pair<P0, P1>& e ) { return this->insert( i, e ); }, insert )
	REGIST_CLASSMETHOD_OVERLOAD( iterator( iterator ), erase, erase )
	REGIST_CLASSMETHOD_OVERLOAD( iterator(), begin, begin )
	REGIST_CLASSMETHOD_OVERLOAD( iterator(), end, end )
	REGIST_CLASSMETHOD_OVERLOAD( reverse_iterator(), rbegin, rbegin )
	REGIST_CLASSMETHOD_OVERLOAD( reverse_iterator(), rend, rend )
	REGIST_CLASSMETHOD_OVERLOAD( iterator(const P0&), find, find )
DEFINE_TEMPLATE_END()

DEFINE_NS_TEMPLATE_BEGIN_WITH_2_PARAMS( std, multimap, typename, typename )
	REGIST_DEFAULT_CONSTRUCTOR()
	REGIST_ITERATOR( iterator )
	REGIST_ITERATOR( reverse_iterator )
	REGIST_CLASSMETHOD( empty )
	REGIST_CLASSMETHOD( size )
	REGIST_CLASSMETHOD_WITH_LAMBDA( iterator( iterator, const std::pair<P0, P1>& ), [this]( iterator i, const std::pair<P0, P1>& e ) { return this->insert( i, e ); }, insert )
	REGIST_CLASSMETHOD_OVERLOAD( iterator( iterator ), erase, erase )
	REGIST_CLASSMETHOD_OVERLOAD( iterator(), begin, begin )
	REGIST_CLASSMETHOD_OVERLOAD( iterator(), end, end )
	REGIST_CLASSMETHOD_OVERLOAD( reverse_iterator(), rbegin, rbegin )
	REGIST_CLASSMETHOD_OVERLOAD( reverse_iterator(), rend, rend )
	REGIST_CLASSMETHOD_OVERLOAD( iterator(const P0&), find, find )
DEFINE_TEMPLATE_END()

DEFINE_NS_TEMPLATE_BEGIN_WITH_1_PARAM( std, list, typename )
	REGIST_DEFAULT_CONSTRUCTOR()
	REGIST_ITERATOR( iterator )
	REGIST_ITERATOR( reverse_iterator )
	REGIST_CLASSMETHOD( empty )
	REGIST_CLASSMETHOD( size )
	REGIST_CLASSMETHOD_WITH_LAMBDA( iterator( iterator, const P0& ), [this]( iterator i, const P0& e ) { return this->insert( i, e ); }, insert )
	REGIST_CLASSMETHOD_OVERLOAD( iterator( iterator ), erase, erase )
	REGIST_CLASSMETHOD_OVERLOAD( iterator(), begin, begin )
	REGIST_CLASSMETHOD_OVERLOAD( iterator(), end, end )
	REGIST_CLASSMETHOD_OVERLOAD( reverse_iterator(), rbegin, rbegin )
	REGIST_CLASSMETHOD_OVERLOAD( reverse_iterator(), rend, rend )
DEFINE_TEMPLATE_END()

DEFINE_NS_TEMPLATE_BEGIN_WITH_1_PARAM( std, vector, typename )
	REGIST_DEFAULT_CONSTRUCTOR()
	REGIST_ARRAY( P0, size )
	REGIST_ITERATOR( iterator )
	REGIST_ITERATOR( reverse_iterator )
	REGIST_CLASSMETHOD( empty )
	REGIST_CLASSMETHOD_WITH_LAMBDA( iterator( iterator, const P0& ), [this]( iterator i, const P0& e ) { return this->insert( i, e ); }, insert )
	REGIST_CLASSMETHOD_WITH_LAMBDA( iterator( iterator ), [this]( iterator i ) { return this->erase( i ); }, erase )
	REGIST_CLASSMETHOD_OVERLOAD( P0&(typename std::vector<P0>::size_type), at, at )
	REGIST_CLASSMETHOD_OVERLOAD( iterator(), begin, begin )
	REGIST_CLASSMETHOD_OVERLOAD( iterator(), end, end )
	REGIST_CLASSMETHOD_OVERLOAD( reverse_iterator(), rbegin, rbegin )
	REGIST_CLASSMETHOD_OVERLOAD( reverse_iterator(), rend, rend )
DEFINE_TEMPLATE_END()

DEFINE_NS_TEMPLATE_BEGIN_WITH_1_PARAM( std, basic_string, typename )
	REGIST_DEFAULT_CONSTRUCTOR()
	REGIST_ITERATOR( iterator )
	REGIST_ITERATOR( reverse_iterator )
	REGIST_CLASSMETHOD( empty )
	REGIST_CLASSMETHOD( size )
	REGIST_CLASSMETHOD( c_str )
	REGIST_CLASSMETHOD_WITH_LAMBDA( iterator( iterator, const P0 ), [this]( iterator i, const P0 e ) { return this->insert( i, e ); }, insert )
	REGIST_CLASSMETHOD_WITH_LAMBDA( iterator( iterator ), [this]( iterator i ) { return this->erase( i ); }, erase )
	REGIST_CLASSMETHOD_OVERLOAD( iterator(), begin, begin )
	REGIST_CLASSMETHOD_OVERLOAD( iterator(), end, end )
	REGIST_CLASSMETHOD_OVERLOAD( reverse_iterator(), rbegin, rbegin )
	REGIST_CLASSMETHOD_OVERLOAD( reverse_iterator(), rend, rend )
DEFINE_TEMPLATE_END()

DEFINE_NS_TEMPLATE_BEGIN_WITH_1_PARAM( std, unique_ptr, typename )
	REGIST_CONSTRUCTOR_BEGIN()
		REGIST_CUSTOM_CONSTRUCTOR( P0* )
	REGIST_CONSTRUCTOR_END()
	REGIST_AS_STRONG_POINTER()
	REGIST_CLASSMETHOD_OVERLOAD( void(), reset, Reset )
	REGIST_CLASSMETHOD_OVERLOAD( void(), reset, reset )
DEFINE_TEMPLATE_END()

DEFINE_NS_TEMPLATE_BEGIN_WITH_1_PARAM( std, shared_ptr, typename )
	REGIST_CONSTRUCTOR_BEGIN()
		REGIST_CUSTOM_CONSTRUCTOR( const std::weak_ptr<P0>& )
		REGIST_CUSTOM_CONSTRUCTOR( P0* )
	REGIST_CONSTRUCTOR_END()
	REGIST_AS_STRONG_POINTER()
	REGIST_CLASSMETHOD_OVERLOAD( void(), reset, Reset )
	REGIST_CLASSMETHOD_OVERLOAD( void(), reset, reset )
DEFINE_TEMPLATE_END()

DEFINE_NS_TEMPLATE_BEGIN_WITH_1_PARAM( std, weak_ptr, typename )
	REGIST_CONSTRUCTOR_BEGIN()
		REGIST_CUSTOM_CONSTRUCTOR( const std::shared_ptr<P0>& )
	REGIST_CONSTRUCTOR_END()
	REGIST_AS_WEAK_POINTER_IMPLEMENT( std::shared_ptr<P0> )
	REGIST_CLASSMETHOD_OVERLOAD( void(), reset, Reset )
	REGIST_CLASSMETHOD_OVERLOAD( void(), reset, reset )
DEFINE_TEMPLATE_END()